# Generated by Django 4.0.5 on 2022-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=20)),
                ('pesan', models.TextField(max_length=50)),
            ],
        ),
    ]
